#!/bin/bash

DATA_ROOT=/ssd2/tailbench/tailbench.inputs
SERVER_PORT=7312
QPS=1
THREADS=1
AUDIO_SAMPLES='audio_samples'
MINSLEEPNS=10000

TBENCH_SERVER=147.46.242.201 TBENCH_SERVER_PORT=${SERVER_PORT} TBENCH_CLIENT_THREADS=${THREADS} TBENCH_QPS=${QPS} TBENCH_RANDSEED=${RAND_SEED} TBENCH_MINSLEEPNS=${MINSLEEPNS} TBENCH_AN4_CORPUS=${DATA_ROOT}/sphinx \
    TBENCH_AUDIO_SAMPLES=${AUDIO_SAMPLES} ./decoder_client_networked &
